# -*- coding: utf-8 -*-

from setuptools import setup

setup(
    name="alarmdecoder-webapp",
    version='0.8.6',
    url='https://github.com/nutechsoftware/alarmdecoder-webapp',
    description='AlarmDecoder-webapp provides a web interface for your AlarmDecoder device.',
    author='Nu Tech Software Solutions, Inc.',
    author_email='ad2usb@support.nutech.com',
    packages=["ad2web"],
    include_package_data=True,
    zip_safe=False,
    python_requires='>=3.6',
    install_requires=[
        'Flask',
        'Flask-SQLAlchemy',
        'Flask-WTF',
        'Flask-Babel',
        'Flask-Testing',
        'Flask-Mail',
        'Flask-Cache',
        'Flask-Login',
        'Flask-OpenID',
        'pytest',
        'alarmdecoder>=0.9',
        'pyopenssl',
        'jsonpickle',
        'psutil>=2.0.0',
        'sh',
        'alembic',
        'netifaces',
    ],
    test_suite='tests',
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Environment :: Web Environment',
        'License :: OSI Approved :: BSD License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
        'Topic :: Software Development :: Libraries',
        'Topic :: Communications',
        'Topic :: Home Automation',
        'Topic :: Security',
    ]
)
