# -*- coding: utf-8 -*-

from setuptools import setup

setup(
    name="alarmdecoder-webapp",
    version='0.8.6',
    url='https://github.com/nutechsoftware/alarmdecoder-webapp',
    description='AlarmDecoder-webapp provides a web interface for your AlarmDecoder device.',
    author='Nu Tech Software Solutions, Inc.',
    author_email='ad2usb@support.nutech.com',
    packages=["ad2web"],
    include_package_data=True,
    zip_safe=False,
    python_requires='>=3.6',
    install_requires=[
        'Flask>=2.0',
        'Flask-SQLAlchemy>=3.0',
        'Flask-WTF>=1.0',
        'Flask-Babel>=3.0',
        'Flask-Testing>=0.8',
        'Flask-Mail>=0.9',
        'flask-caching>=1.10',
        'Flask-Login>=0.6',
        'Flask-OpenID>=1.3',
        'flask-socketio>=5.0',
        'python-socketio>=5.0',
        'pytest>=7.0',
        'alarmdecoder>=1.13',
        'pyopenssl>=21.0',
        'jsonpickle>=1.5',
        'psutil>=5.0',
        'sh>=2.0',
        'alembic>=1.0',
        'netifaces>=0.10',
        'gevent>=21.12',
        'markupsafe>=2.0',
        'click',
    ],
    test_suite='tests',
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Environment :: Web Environment',
        'License :: OSI Approved :: BSD License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
        'Topic :: Software Development :: Libraries',
        'Topic :: Communications',
        'Topic :: Home Automation',
        'Topic :: Security',
    ]
)
